### ISSUE TITLE
Able to view result of a search location on the application

### ISSUE THREAD

**Issue by HEARTOFAL1ON** [CS2103JAN2018-T09-B4/main#62]
for project supervisor @jeffryhartanto to take note and KIV
(sorry for tagging if unnecessary :x)

**Comment by jeffryhartanto** [comment]
@HEARTOFAL1ON Please follow our guideline for creating issue. Problems with the name and labels.

**Comment by HEARTOFAL1ON** [comment]
major enhancement

**Comment by HEARTOFAL1ON** [comment]
Ignore previous comment, no need to make use of any Google Maps API

Reference to this issue I created in "issues" forums: https://github.com/nus-cs2103-AY1718S2/forum/issues/36

**Comment by HEARTOFAL1ON** [comment]
#109 (incomplete still)
