### ISSUE TITLE
Update DG

### ISSUE THREAD

**Issue by marlenekoh** [CS2103JAN2018-T09-B4/main#79]
TODO:

**Comment by chenxing1992** [comment]
This issue will also update Jeffery's commenting for DG as well.

**Comment by chenxing1992** [comment]
#88 
- update NFR, Glossary and include introduction
- include Use Case

**Comment by T09B4** [comment]
#97 
Added Use Case
Removed Appendix A
Added links to TOC
Edited implementation of journal window + diagram
